Don't raise exception when committing without transaction.
Flush instead.
It makes integrating with third-party libraries easier, because you
can simply call session.commit() instead of session.flush().

Without this change calling .commit() outside of transaction would
raise:
  sqlalchemy.exc.InvalidRequestError: No transaction is begun.